//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonXinThue
    {
        public System.DateTime ThoiGianXin { get; set; }
        public string MucDich { get; set; }
        public int ThoiHan { get; set; }
        public string TenDangNhap { get; set; }
        public string MaMB { get; set; }
        public string MaNV { get; set; }
        public short MATT { get; set; }
        public string MaHD { get; set; }
    
        public virtual NguoiThue NguoiThue { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual MatBang MatBang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
