//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiThue()
        {
            this.DonXinThues = new HashSet<DonXinThue>();
            this.SuKienUuDais = new HashSet<SuKienUuDai>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string CMND { get; set; }
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonXinThue> DonXinThues { get; set; }
        public virtual ThongTinND ThongTinND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKienUuDai> SuKienUuDais { get; set; }

        // -- Not Mapped -- //
        public string rePassword { get; set; }
    }
}
