//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKienUuDai
    {
        public System.DateTime NgayLamDon { get; set; }
        public string MaDM { get; set; }
        public string TenDangNhap { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string HinhBia { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public short MATT { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NguoiThue NguoiThue { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
