//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuChi
    {
        public System.DateTime ThoiGian { get; set; }
        public string HinhThuc { get; set; }
        public double SoTien { get; set; }
        public string NoiDung { get; set; }
        public int MaLuong { get; set; }
        public string MaNV { get; set; }
        public short MATT { get; set; }
    
        public virtual Luong Luong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
