//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienThue
    {
        public string MaTienThue { get; set; }
        public string SoTienNo { get; set; }
        public string MaHD { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
